### ISSUE TITLE
读取nginx_access.csv文件时报错: 不知道怎么处理.

### ISSUE THREAD

**Issue by yulk** [CapAllen/Dashboard#1]
读取nginx_access.csv文件时报错: 不知道怎么处理.

  File "D:\git_hub\Dashboard\help_funcs.py", line 503, in pre_linkage_data
    data_for_line = pd.DataFrame(df_nginx.groupby(0)[2].value_counts().sort_index()).rename(columns={2:'count'}).unstack(0)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1

**Comment by CapAllen** [comment]
这里是因为在`help_funcs.py`第500行筛选之后，数据样本为空导致的。你重新下载一下`nginx_access.csv`文件，并且把`help_funcs.py`文件中的第500行注释掉就好了。
